import IISInformacionnokonsultacionnaya_sistemaSizeEController from '../i-i-s-informacionnokonsultacionnaya-sistema-size-e';

var IISInformacionnokonsultacionnaya_sistemaSizeENewController = IISInformacionnokonsultacionnaya_sistemaSizeEController;
export default IISInformacionnokonsultacionnaya_sistemaSizeENewController;
