//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Informacionnokonsultacionnaya_sistema
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Component.
    /// </summary>
    // *** Start programmer edit section *** (Component CustomAttributes)

    // *** End programmer edit section *** (Component CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ComponentE", new string[] {
            "Name as \'Наименование\'"})]
    [View("ComponentL", new string[] {
            "Name as \'Наименование\'"})]
    public class Component : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Component CustomMembers)

        // *** End programmer edit section *** (Component CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Component.Name CustomAttributes)

        // *** End programmer edit section *** (Component.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Component.Name Get start)

                // *** End programmer edit section *** (Component.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Component.Name Get end)

                // *** End programmer edit section *** (Component.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Component.Name Set start)

                // *** End programmer edit section *** (Component.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Component.Name Set end)

                // *** End programmer edit section *** (Component.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ComponentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ComponentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ComponentE", typeof(IIS.Informacionnokonsultacionnaya_sistema.Component));
                }
            }
            
            /// <summary>
            /// "ComponentL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ComponentL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ComponentL", typeof(IIS.Informacionnokonsultacionnaya_sistema.Component));
                }
            }
        }
    }
}
