//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Informacionnokonsultacionnaya_sistema
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Form.
    /// </summary>
    // *** Start programmer edit section *** (Form CustomAttributes)

    // *** End programmer edit section *** (Form CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("FormE", new string[] {
            "Name as \'Name\'"})]
    [View("FormL", new string[] {
            "Name as \'Name\'"})]
    public class Form : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Form CustomMembers)

        // *** End programmer edit section *** (Form CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Form.Name CustomAttributes)

        // *** End programmer edit section *** (Form.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Form.Name Get start)

                // *** End programmer edit section *** (Form.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Form.Name Get end)

                // *** End programmer edit section *** (Form.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Form.Name Set start)

                // *** End programmer edit section *** (Form.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Form.Name Set end)

                // *** End programmer edit section *** (Form.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "FormE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FormE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FormE", typeof(IIS.Informacionnokonsultacionnaya_sistema.Form));
                }
            }
            
            /// <summary>
            /// "FormL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View FormL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("FormL", typeof(IIS.Informacionnokonsultacionnaya_sistema.Form));
                }
            }
        }
    }
}
