//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Informacionnokonsultacionnaya_sistema
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// List industry.
    /// </summary>
    // *** Start programmer edit section *** (ListIndustry CustomAttributes)

    // *** End programmer edit section *** (ListIndustry CustomAttributes)
    [AutoAltered()]
    [Caption("List industry")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ListIndustryE", new string[] {
            "Name as \'Name\'",
            "Subindustry as \'Subindustry\'",
            "Subindustry.Name as \'Name\'"}, Hidden=new string[] {
            "Name",
            "Subindustry.Name"})]
    [MasterViewDefineAttribute("ListIndustryE", "Subindustry", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    public class ListIndustry : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.Informacionnokonsultacionnaya_sistema.Subindustry fSubindustry;
        
        private IIS.Informacionnokonsultacionnaya_sistema.Support fSupport;
        
        // *** Start programmer edit section *** (ListIndustry CustomMembers)

        // *** End programmer edit section *** (ListIndustry CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ListIndustry.Name CustomAttributes)

        // *** End programmer edit section *** (ListIndustry.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ListIndustry.Name Get start)

                // *** End programmer edit section *** (ListIndustry.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ListIndustry.Name Get end)

                // *** End programmer edit section *** (ListIndustry.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ListIndustry.Name Set start)

                // *** End programmer edit section *** (ListIndustry.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ListIndustry.Name Set end)

                // *** End programmer edit section *** (ListIndustry.Name Set end)
            }
        }
        
        /// <summary>
        /// List industry.
        /// </summary>
        // *** Start programmer edit section *** (ListIndustry.Subindustry CustomAttributes)

        // *** End programmer edit section *** (ListIndustry.Subindustry CustomAttributes)
        [NotNull()]
        public virtual IIS.Informacionnokonsultacionnaya_sistema.Subindustry Subindustry
        {
            get
            {
                // *** Start programmer edit section *** (ListIndustry.Subindustry Get start)

                // *** End programmer edit section *** (ListIndustry.Subindustry Get start)
                IIS.Informacionnokonsultacionnaya_sistema.Subindustry result = this.fSubindustry;
                // *** Start programmer edit section *** (ListIndustry.Subindustry Get end)

                // *** End programmer edit section *** (ListIndustry.Subindustry Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ListIndustry.Subindustry Set start)

                // *** End programmer edit section *** (ListIndustry.Subindustry Set start)
                this.fSubindustry = value;
                // *** Start programmer edit section *** (ListIndustry.Subindustry Set end)

                // *** End programmer edit section *** (ListIndustry.Subindustry Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Informacionnokonsultacionnaya_sistema.Support.
        /// </summary>
        // *** Start programmer edit section *** (ListIndustry.Support CustomAttributes)

        // *** End programmer edit section *** (ListIndustry.Support CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Informacionnokonsultacionnaya_sistema.Support Support
        {
            get
            {
                // *** Start programmer edit section *** (ListIndustry.Support Get start)

                // *** End programmer edit section *** (ListIndustry.Support Get start)
                IIS.Informacionnokonsultacionnaya_sistema.Support result = this.fSupport;
                // *** Start programmer edit section *** (ListIndustry.Support Get end)

                // *** End programmer edit section *** (ListIndustry.Support Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ListIndustry.Support Set start)

                // *** End programmer edit section *** (ListIndustry.Support Set start)
                this.fSupport = value;
                // *** Start programmer edit section *** (ListIndustry.Support Set end)

                // *** End programmer edit section *** (ListIndustry.Support Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ListIndustryE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ListIndustryE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ListIndustryE", typeof(IIS.Informacionnokonsultacionnaya_sistema.ListIndustry));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ListIndustry.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfListIndustry CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfListIndustry CustomAttributes)
    public class DetailArrayOfListIndustry : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Informacionnokonsultacionnaya_sistema.DetailArrayOfListIndustry members)

        // *** End programmer edit section *** (IIS.Informacionnokonsultacionnaya_sistema.DetailArrayOfListIndustry members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ListIndustry by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ListIndustry.
        /// </summary>
        public DetailArrayOfListIndustry(IIS.Informacionnokonsultacionnaya_sistema.Support fSupport) : 
                base(typeof(ListIndustry), ((ICSSoft.STORMNET.DataObject)(fSupport)))
        {
        }
        
        public IIS.Informacionnokonsultacionnaya_sistema.ListIndustry this[int index]
        {
            get
            {
                return ((IIS.Informacionnokonsultacionnaya_sistema.ListIndustry)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Informacionnokonsultacionnaya_sistema.ListIndustry dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
