//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Informacionnokonsultacionnaya_sistema
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Subindustry.
    /// </summary>
    // *** Start programmer edit section *** (Subindustry CustomAttributes)

    // *** End programmer edit section *** (Subindustry CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SubindustryE", new string[] {
            "Name as \'Name\'"})]
    [View("SubindustryL", new string[] {
            "Name as \'Name\'"})]
    public class Subindustry : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        // *** Start programmer edit section *** (Subindustry CustomMembers)

        // *** End programmer edit section *** (Subindustry CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Subindustry.Name CustomAttributes)

        // *** End programmer edit section *** (Subindustry.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Subindustry.Name Get start)

                // *** End programmer edit section *** (Subindustry.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Subindustry.Name Get end)

                // *** End programmer edit section *** (Subindustry.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Subindustry.Name Set start)

                // *** End programmer edit section *** (Subindustry.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Subindustry.Name Set end)

                // *** End programmer edit section *** (Subindustry.Name Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SubindustryE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubindustryE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubindustryE", typeof(IIS.Informacionnokonsultacionnaya_sistema.Subindustry));
                }
            }
            
            /// <summary>
            /// "SubindustryL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SubindustryL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SubindustryL", typeof(IIS.Informacionnokonsultacionnaya_sistema.Subindustry));
                }
            }
        }
    }
}
