import IISInformacionnokonsultacionnaya_sistemaInvestmentEController from '../i-i-s-informacionnokonsultacionnaya-sistema-investment-e';

var IISInformacionnokonsultacionnaya_sistemaInvestmentENewController = IISInformacionnokonsultacionnaya_sistemaInvestmentEController;
export default IISInformacionnokonsultacionnaya_sistemaInvestmentENewController;
